version: '3.6'

services:
  app:
    container_name: scrum-poker
    build:
      context: .
      target: production
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file: .env
    command: node dist/backend/main
