version: '3.6'

services:
  app:
    container_name: scrum-poker
    build:
      context: .
      target: production
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file: .env
    labels:
      - wud.watch=false
