export default [
	"avontuurlijk (adventurous)",
	"behulpzaam (helpful)",
	"belangstellend (interested)",
	"bescheiden (modest)",
	"betrouwbaar (reliable)",
	"direct",
	"doorzetter (go-getter)",
	"duidelijk (clear)",
	"eerlijk (honest)",
	"enthousiast (enthousiast)",
	"er verzorgd uitzien (looking the part)",
	"evenwichtig (balanced)",
	"gedisciplineerd (disciplined)",
	"geduldig (patient)",
	"genieter (enjoyer)",
	"gestructureerd (structured)",
	"gevoeglig (sensitive)",
	"gul (generous)",
	"handig (handy)",
	"humoristisch (funny)",
	"ijverig (diligent)",
	"insprirerend (inspiring)",
	"intelligent (intelligent)",
	"krachtig (powerful)",
	"makkelijke prater (easy talker)",
	"nuchter (sober)",
	"ontspannend (relaxed)",
	"open",
	"optimistisch (optimistic)",
	"overtuigend (convincingly)",
	"respectvol (respectful)",
	"rustig (easy going)",
	"serieus (seriously)",
	"tevreden (content)",
	"veelzijdig (versatile)",
	"voor jezelf opkomen (standing up for yourself)",
	"vriendelijk (kind)",
	"zelfstandig (independent)",
	"zelfverzekerd (confident)",
	"zorgvuldig (careful)",
	"ambitieus (ambitious)",
	"analytisch (analytical)",
	"bedachtzaam (thoughtful)",
	"bemiddelaar (mediator)",
	"consequent (consistently)",
	"creatief (creative)",
	"doelgericht (goal oriented)",
	"flexibel (flexible)",
	"idealistisch (idealistic)",
	"initiatiefrijk (takes initiative)",
	"inlevingsvermogen (empathy)",
	"kan goed luisteren (is good listener)",
	"kan relativeren (can put into perspective)",
	"mild",
	"moedig (brave)",
	"onderscheidingsvermogen (discernment)",
	"oplettend (attentive)",
	"organisator (organizer)",
	"praktisch (practical)",
	"speels (playful)",
	"spontaan (spontanious)",
	"tactvol",
	"toegewijd (dedicated)",
	"tolerant",
	"vastberaden (determined)",
	"verantwoordelijk (responsible)",
	"vernieuwend (innovative)",
	"vrolijk (happy)",
	"zich kunnen concentreren (focussed)",
	"zorgzaam (caring)",
	"energiek (energetic)",
];
