export default [
	"avontuurlijk (adventurous)",
	"behulpzaam (helpful)",
	"belangstellend (shows interest in others)",
	"bescheiden (modest)",
	"betrouwbaar (reliable)",
	"direct",
	"doorzetter (go-getter)",
	"duidelijk (clear)",
	"eerlijk (honest)",
	"enthousiast (enthousiast)",
	"er verzorgd uitzien (takes care of his/her physical appearance)",
	"evenwichtig (well balanced)",
	"gedisciplineerd (disciplined)",
	"geduldig (patient)",
	"genieter (enjoyer)",
	"gestructureerd (structured)",
	"gevoeglig (sensitive)",
	"gul (generous)",
	"handig (handy)",
	"humoristisch (funny)",
	"ijverig (diligent)",
	"insprirerend (inspiring)",
	"intelligent (intelligent)",
	"krachtig (powerful)",
	"makkelijke prater (easy talker)",
	"nuchter (sober)",
	"ontspannend (relaxed)",
	"open",
	"optimistisch (optimistic)",
	"overtuigend (convincing)",
	"respectvol (respectful)",
	"rustig (easy going)",
	"serieus (seriousl)",
	"tevreden (content)",
	"veelzijdig (versatile)",
	"voor jezelf opkomen (standing up for yourself)",
	"vriendelijk (kind)",
	"zelfstandig (independent)",
	"zelfverzekerd (confident)",
	"zorgvuldig (careful)",
	"ambitieus (ambitious)",
	"analytisch (analytical)",
	"bedachtzaam (thoughtful)",
	"bemiddelaar (mediator)",
	"consequent (consequent)",
	"creatief (creative)",
	"doelgericht (goal oriented)",
	"flexibel (flexible)",
	"idealistisch (idealistic)",
	"initiatiefrijk (takes initiative)",
	"inlevingsvermogen (shows empathy)",
	"kan goed luisteren (is a good listener)",
	"kan relativeren (can put things into perspective)",
	"mild",
	"moedig (brave)",
	"onderscheidingsvermogen (discernment)",
	"oplettend (attentive)",
	"organisator (organizer)",
	"praktisch (practical)",
	"speels (playful)",
	"spontaan (spontanious)",
	"tactvol (tactful)" ,
	"toegewijd (dedicated)",
	"tolerant",
	"vastberaden (determined)",
	"verantwoordelijk (responsible)",
	"vernieuwend (innovative)",
	"vrolijk (happy)",
	"zich kunnen concentreren (focussed)",
	"zorgzaam (caring)",
	"energiek (energetic)",
];
